---
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

# Each version of NetBox listed here must have a corresponding directory/configuration file 
# under development/netbox_<NETBOX_VER>/configuration.py
env:
- NETBOX_VER=v2.8.3
- NETBOX_VER=master

services:
  - docker

before_script:
  - pip install invoke docker-compose poetry

script:
  - invoke build --python-ver $TRAVIS_PYTHON_VERSION
  - invoke tests
